export module effects;
import Building;
import card;
import Player;
import board;
import bank;
import std;

export void addCoins(Player& player, const Card& card);
export void addVictorypoints(Player& player, const Card& card);
export void addResources(Player& player, const Building& card);
//export void addEveryResource(Player& player, const Building& card);
//export void addShields(bool player, Board& board);
export void addScientificSymbol(Player& player, const Building& card);
export void threeCoinsPerGray(Player& player);
export void twoCoinsPerBrown(Player& player);
export void oneCoinPerYellow(Player& player);
export void oneCoinPerRed(Player& player);
export void tradersGuild(Player& player1, Player& player2);
export void loseThreeCoins(Player& player, Bank& bank);
export void discardGrey(Player& player, std::uint8_t idCard);