export module effects;
import Building;
import card;
import Player;
import board; 
import std;

export void addCoins(Player& player, const Card& card);
export void addVictorypoints(Player& player, const Card& card);
export void addResources(Player& player, const Building& card);
export void chooseRawResource(Player& player);
export void chooseManufacturedGood(Player& player);
export void addShields(bool player, Board& board, const Card& card);
export void addScientificSymbol(Player& player, const Building& card);
export void threeCoinsPerGray(Player& player);
export void twoCoinsPerBrown(Player& player);
export void oneCoinPerYellow(Player& player);
export void oneCoinPerRed(Player& player);
export void buildersGuild(Player& player1, const Player& player2, bool endGame);
export void tradersGuild(Player& player1, const Player& player2, bool endGame);
export void moneylendersGuild(Player& player1, const Player& player2, bool endGame);
export void magistratesGuild(Player& player1, const Player& player2, bool endGame);
export void scientistsGuild(Player& player1, const Player& player2, bool endGame);
export void tacticiansGuild(Player& player1, const Player& player2, bool endGame);
export void shipownersGuild(Player& player1, const Player& player2, bool endGame);
export void loseThreeCoins(Player& player);
export void discardGrey(Player& player, std::uint8_t idCard, std::vector<std::shared_ptr<Card>>& discardedCards);
export void discardBrown(Player& player, std::uint8_t idCard, std::vector<std::shared_ptr<Card>>& discardedCards);
export void twoCoinsPerWonder(Player& player);
//export void drawProgress(Player& player)